#!/bin/sh

# Copyright 2015-2021 IQRF Tech s.r.o.
# Copyright 2019-2021 MICRORISC s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e

# Automatically added by dh_installinit/13.1
if [ -x "/etc/init.d/iqrf-gateway-daemon" ] && [ "$1" = remove ]; then
  invoke-rc.d iqrf-gateway-daemon stop || exit 1
fi
# End automatically added section

# Automatically added by dh_systemd_start/13.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop 'iqrf-gateway-daemon.service' >/dev/null || true
fi
# End automatically added section

if [ "$1" = "upgrade" ]; then
  # Remove old IQRF Repository cache directories
  for dir in server companies manufacturers osdpa products standards packages; do
    rm -rf /var/cache/iqrf-gateway-daemon/iqrfRepoCache/${dir:?}
  done
fi
